---
abstract: 'Plugin to define route handlers with a timeout'
author:
  - 'Frederic Lechauve'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.120921'
license: restrictive
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-TimeoutManager
requires:
  Dancer: 1.3120
version: 0.05
